version: '3.8'
services:
  db: 
    image: postgres:12
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=macizomedia
      - POSTGRES_PASSWORD=arepas2135
      - POSTGRES_DB=mmcs_dogoapp_db_dev_1